### PR TITLE
Fix param defaults for Ubuntu > 12.04 (and implement Beaker for acceptance tests)

### PR DESCRIPTION
**Pull request by mcrumm**
Module defaults (i.e, `include composer`) fail on `Augeas['whitelist_phar']` for Ubuntu > 12.04.

This PR will default to `suhosin_enabled=false` for Ubuntu releases > 12.04, since suhosin no longer ships with versions newer than precise.

In order to prove the existence of the bug, and to ease testing multiple distros, I refactored `composer_spec.rb` to use shared examples, and added an acceptance test for `composer::project`, using [Beaker](https://github.com/puppetlabs/beaker).

I also updated the README to include information on running beaker tests, including how to provide a GitHub auth token to beaker via hiera.

### CODE REVIEW

**Comment by mcrumm** [comment]
Sorry for all the extra travis commits -- I didn't get all the excludes configured properly the first time around.

The 1.8.7 builds are failing (an issue with the `il8n` gem, it appears), but all others pass without issue.

**Comment by andyshinn** [comment]
Beaker is something we should definitely get hooked up. Thanks for taking the plunge!

I'm all for this in general. I'll take a look at the current failures and review in the next week or so. Sorry, I'm a little backed up on other paid work at the moment.

In the meantime, can you squash the travis commits? I'll see if we can safely drop Ruby 1.8.x support.

**Comment by mcrumm** [comment]
Sorry for lumping beaker into the bugfix PR -- I can split the two if that makes things simpler.

**Comment by andyshinn** [comment]
I think the fix and Beaker do make more sense as separate PRs. Beaker is a new way of testing and something I would like to get familiar with myself. I can certainly get the ultimate fix for the issue out much faster if you could do that. I appreciate it!

**Comment by mcrumm** [comment]
No problem!  I'll close this PR and split into two.

**Pull request closed without merging**
